spring:
  application:
    name: busylight

logging:
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger:%line - %yellow(%msg %n)"
  level:
    root: INFO
    l9g: DEBUG

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: info,health,metrics

springdoc:
  api-docs:
    path: "/api-docs"
  show-actuator: true

server:
  port: 31415
  address: 127.0.0.1

usb-device:
  vendor-id: 0x04D8
  product-id: 0xF372
